/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package getMeMovin;

import Views.LoginPanel;
import java.awt.CardLayout;
import java.awt.Component;

/**
 *
 * @author jkustan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    
    CardLayout cardLayout;
    
    public Main() {
        initComponents();
        
        cardLayout = (CardLayout) (panelContainer.getLayout());
        initLogin();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        splitNavigation = new javax.swing.JPanel();
        btnMovie = new javax.swing.JButton();
        btnActor = new javax.swing.JButton();
        btnDirector = new javax.swing.JButton();
        panelContainer = new javax.swing.JPanel();
        jPanelMovie = new javax.swing.JPanel();
        jPanelActor = new javax.swing.JPanel();
        jPanelDirector = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane.setDividerSize(1);

        splitNavigation.setBackground(new java.awt.Color(51, 51, 51));

        btnMovie.setBackground(new java.awt.Color(51, 51, 51));
        btnMovie.setText("Movie");
        btnMovie.setBorder(null);
        btnMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieActionPerformed(evt);
            }
        });

        btnActor.setBackground(new java.awt.Color(51, 51, 51));
        btnActor.setText("Actor");
        btnActor.setBorder(null);
        btnActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActorActionPerformed(evt);
            }
        });

        btnDirector.setBackground(new java.awt.Color(51, 51, 51));
        btnDirector.setText("Director");
        btnDirector.setBorder(null);
        btnDirector.setBorderPainted(false);
        btnDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout splitNavigationLayout = new javax.swing.GroupLayout(splitNavigation);
        splitNavigation.setLayout(splitNavigationLayout);
        splitNavigationLayout.setHorizontalGroup(
            splitNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splitNavigationLayout.createSequentialGroup()
                .addGroup(splitNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        splitNavigationLayout.setVerticalGroup(
            splitNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splitNavigationLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(splitNavigation);

        panelContainer.setLayout(new java.awt.CardLayout());

        jPanelMovie.setBackground(new java.awt.Color(54, 58, 58));
        jPanelMovie.setName("jPanelMovie"); // NOI18N

        javax.swing.GroupLayout jPanelMovieLayout = new javax.swing.GroupLayout(jPanelMovie);
        jPanelMovie.setLayout(jPanelMovieLayout);
        jPanelMovieLayout.setHorizontalGroup(
            jPanelMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanelMovieLayout.setVerticalGroup(
            jPanelMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        panelContainer.add(jPanelMovie, "jPanelMovie");

        jPanelActor.setBackground(new java.awt.Color(52, 54, 54));
        jPanelActor.setName("jPanelActor"); // NOI18N

        javax.swing.GroupLayout jPanelActorLayout = new javax.swing.GroupLayout(jPanelActor);
        jPanelActor.setLayout(jPanelActorLayout);
        jPanelActorLayout.setHorizontalGroup(
            jPanelActorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanelActorLayout.setVerticalGroup(
            jPanelActorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        panelContainer.add(jPanelActor, "jPanelActor");

        jPanelDirector.setBackground(new java.awt.Color(48, 50, 50));
        jPanelDirector.setName("jPanelDirector"); // NOI18N

        javax.swing.GroupLayout jPanelDirectorLayout = new javax.swing.GroupLayout(jPanelDirector);
        jPanelDirector.setLayout(jPanelDirectorLayout);
        jPanelDirectorLayout.setHorizontalGroup(
            jPanelDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanelDirectorLayout.setVerticalGroup(
            jPanelDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        panelContainer.add(jPanelDirector, "jPanelDirector");

        jSplitPane.setRightComponent(panelContainer);

        jMenuBar.setBorder(null);

        jMenuFile.setText("File");
        jMenuBar.add(jMenuFile);

        jMenu2.setText("Edit");
        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieActionPerformed
        cardLayout.show(panelContainer,"jPanelMovie");  
    }//GEN-LAST:event_btnMovieActionPerformed

    private void btnActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActorActionPerformed
        cardLayout.show(panelContainer,"jPanelActor");  
    }//GEN-LAST:event_btnActorActionPerformed

    private void btnDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorActionPerformed
         cardLayout.show(panelContainer,"jPanelDirector");  
    }//GEN-LAST:event_btnDirectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActor;
    private javax.swing.JButton btnDirector;
    private javax.swing.JButton btnMovie;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JPanel jPanelActor;
    private javax.swing.JPanel jPanelDirector;
    private javax.swing.JPanel jPanelMovie;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel splitNavigation;
    // End of variables declaration//GEN-END:variables

    private void initLogin() {
        Component loginPanel = new LoginPanel();
        panelContainer.add(loginPanel, "loginPanel");
        toggleNavigation(false);
        cardLayout.show(panelContainer, "loginPanel");
    }

    private void toggleNavigation(boolean isVisible) {
        btnMovie.setVisible(isVisible);
        btnActor.setVisible(isVisible);
        btnDirector.setVisible(isVisible);
    }

    
}
